var options = {
	parse: {
		strict: false,
		filename: process.argv[2]
	},
	compress: {
		sequences: false,
		properties: true,
		dead_code: true,
		drop_debugger: false,
		unsafe: true,
		unsafe_comps: true,
		conditionals: true,
		comparisons: true,
		evaluate: true,
		booleans: true,
		loops: true,
		unused: true,
		hoist_funs: false,
		hoist_vars: false,
		if_return: true,
		join_vars: false,
		cascade: true,
		side_effects: true,
		negate_iife: true,
		screw_ie8: true,

		warnings: false,
		global_defs: {

		}
	},
	output: {
		indent_start: 0,
		indent_level: 4,
		quote_keys: false,
		space_colon: true,
		ascii_only: false,
		inline_script: true,
		width: 80,
		max_line_len: 32000,
		beautify: true,
		source_map: null,
		bracketize: true,
		semicolons: false,
		comments: false,
		preserve_line: true,
		screw_ie8: false
	}
};

var constNames = {
	/////////////
	// blocks //
	/////////////

	BLOCK_ID:0,
	BLOCK_WIDTH:1,
	BLOCK_HEIGHT:2,
	BLOCK_DEPTH:3,
	BLOCK_TEXTURE:4,
	BLOCK_SIZE:32,

	/////////////
	// Chunks //
	/////////////

	CHUNK_X:0,
	CHUNK_Z:1,
	CHUNK_LAST_UPDATED:2,
	CHUNK_TIME_INHABITED:3,

	///////////
	// List //
	///////////

	UINT4:2,
	UINT8:3,
	UINT12:5,
	UINT16:7,
	UINT32:11,
	INT8:6,
	INT16:14,
	INT32:22,
	FLOAT32:33,
	FLOAT64:13,

	///////////////
	// commands //
	///////////////

	COMMAND_REMOTE_ID:0,
	COMMAND_PING:1,
	COMMAND_TIMESTAMP:2,
	COMMAND_ACTION:3,
	COMMAND_VALUE:4,
	// player and control data
	TIMESTAMP: 0,
	LOCALID: 0,
	REMOTEID: 1,
	MOUSE: 2,
	KEYBOARD: 3,
	GAMEPAD: 4,
	PING: 5,
	ACTIVE: 1,
	INACTIVE: 0,
	LEFT_MOUSE: 1,
	MIDDLE_MOUSE: 2,
	RIGHT_MOUSE: 3,
	MOUSE_X: 4,
	MOUSE_Y: 5,
	WHEEL_X: 6,
	WHEEL_Y: 7,

	//controller data
	CROSS: 0,
	CIRCLE: 1,
	TRIANGLE: 2,
	SQUARE: 3,
	LEFT_BUTTON: 4,
	RIGHT_BUTTON: 5,
	LEFT_TRIGGER: 6,
	RIGHT_TRIGGER: 7,
	SELECT: 8,
	START: 9,
	LEFT_ANALOGUE_STICK: 10,
	RIGHT_ANALOGUE_STICK: 11,
	PAD_TOP: 12,
	PAD_BOTTOM: 13,
	PAD_LEFT: 14,
	PAD_RIGHT: 15,

	LEFT_HORIZONTAL: 0,
	LEFT_VERTICAL: 1,
	RIGHT_HORIZONTAL: 2,
	RIGHT_VERTICAL: 3,

	// entity data
	X: 0,
	Y: 1,
	ANGLE: 2,
	WIDTH: 3,
	HEIGHT: 4,
	VELOCITY_X: 5,
	VELOCITY_Y: 6,
	TURNSPEED: 7,
	SPRITE_ID: 8,
	COLOR: 9,
	ALPHA: 10,

	// audio data
	CHUNKID: 0,
	CHUNKSIZE: 1,
	FORMAT: 2,
	SUBCHUNK1ID: 3,
	SUBCHUNK1SIZE: 4,
	AUDIOFORMAT: 5,
	NUMCHANNELS: 6,
	SAMPLERATE: 7,
	BYTERATE: 8,
	BLOCKALIGN: 9,
	BITSPERSAMPLE: 10,
	SUBCHUNK2ID: 11,
	SUBCHUNK2SIZE: 12,

	// actions
	TURNCW: 0,
	MOVEUP: 1,
	TURNCCW: 2,
	MOVEDOWN: 3,
	LIGHTING_X: 4,
	LIGHTING_Y: 5,
	CHANGE_TO_PROJECTION:6,
	CHANGE_TO_CIRCLE:7,
	CHANGE_TO_TRIANGLE:8,
	CHANGE_TO_BEAM:9,
	MOVE_MOUSE_X:0,
	MOVE_MOUSE_Y:1,
	MOUSE_CLICK:2,

	// polygon / light.js data
	R: 7,
	G: 8,
	B: 9,
	RADIUS: 10,
	// circle
	RANGE: 11,
	FALLOFF: 12,
	// viewport
	VIEWPORT_TYPE:7,
	PROJECTION:0,
	CIRCLE:1,
	TRIANGLE:2,
	BEAM:3,
	// other
	TRUE: 1,
	FALSE: 0
};

var engineNames = {
	EMIT_EVENT:"event.emit",
	BLOCK_MAKE:"makeBlock",
	BLOCK_GET:"getBlock",
	COMMAND_EACH:"eachCommand",
	COMMAND_PROCESS:"processCommand",
	COMMAND_ON:"event.on",
	COMMAND_PUSH:"pushCommand",
	COMMAND_MAKE:"newCommand",
	CONFIG_INPUT: "input",
	CONFIG_ACTION: "action",
	CONFIG_MATCH_KEY: "matchKey",
	CONFIG_BINDING: "binding",
	CONFIG_UNBIND: "unbind",
	CONFIG_BIND: "bind",
	CONFIG_LENGTH: "actions",
	CONTROL_PREVENT_DEFAULT: "preventDefault",
	CONTROL_GAMEPADS: "gamepads",
	CONTROL_ON: "event.on",
	CONTROL_EMIT: "event.emit",
	CONTROL_LISTEN: "listen",
	CONTROL_INIT: "initControl",
	GUI_TEMPLATE: "template",
	GUI_REMOVE: "removeGUI",
	GUI_PUT: "putGUI",
	GUI_GET: "getGUI",
	GUI_MAKE: "makeGUI",
	GUI_SET: "setGUI",
	GUI_ON: "event.on",
	GUI_EMIT: "event.emit",
	DRAW_REGISTER_TEXTURE: "registerTexture",
	DRAW_GET_TEXTURE:"getTexture",
	DRAW_MAKE_SPRITE:"makeSprite",
	DRAW_NEW_GRAPHIC: "newGraphic",
	DRAW_GET_GRAPHIC: "getGraphic",
	DRAW_CLEAR: "clear",
	DRAW_CHANGE:"changeState",
	DRAW_POLY: "poly",
	DRAW_MOVE: "reposition",
	DRAW_SETUP: "setupDraw",
	HELP_ITEM_REMOVE: "itemRemove",
	HELP_INDEX_REMOVE: "indexRemove",
	HELP_HAS: "has",
	HELP_SPLICE: "splice",
	LIGHT_SOURCE: "newLight",
	LIGHT_VIEW: "newViewPort",
	LIGHT_WALL: "newWall",
	LIGHT_PARSE: "parseLight",
	LIGHT_ADD_LIGHT: "addLight",
	LIGHT_ADD_VIEW: "addViewPort",
	LIGHT_ADD_WALL: "addWall",
	LIST_CLEAN:"cleanList",
	LIST_SIZE: "size",
	LIST_GET: "getList",
	LIST_PUT: "putList",
	LIST_LINKED: "linked",
	LOOP_GO: "go",
	LOOP_EVERY: "every",
	LOOP_ON: "event.on",
	MAP_MAKE:"makeChunk",
	MAP_DRAW:"drawMap",
	MAP_MOVE:"moveMap",
	PHYSICS_TEST: "test",
	PHYSICS_GET_VERTICES: "getVertices",
	PLAYER_LENGTH: "length",
	PLAYER_REGISTER: "register",
	PLAYER_FIND: "find",
	PLAYER_INIT: "initPlayer",
	PLAYER_IS_LOCAL: "isLocal",
	PLAYER_TOGGLE_PLAYER: "togglePlayer",
	RIFFWAVE_LENGTH: "length",
	RIFFWAVE_GET: "get",
	RIFFWAVE_MAKE: "make",
	STRUCT_MAKE: "makeStruct",
	STRUCT_GET: "getStruct",
	TIME_NOW: "nowTime",
	TIME_MICRO: "micro",
};

var singleNames = {
	EMIT_EVENT:"event.emit",
	BLOCK_MAKE:"Block.make",
	BLOCK_GET:"Block.get",
	COMMAND_EACH:"Command.each",
	COMMAND_PROCESS:"Command.process",
	COMMAND_ON:"Command.on",
	COMMAND_PUSH:"Command.push",
	COMMAND_MAKE:"Command.make",
	CONFIG_INPUT: "Config.input",
	CONFIG_ACTION: "Config.action",
	CONFIG_MATCH_KEY: "Config.matchKey",
	CONFIG_BINDING: "Config.binding",
	CONFIG_UNBIND: "Config.unbind",
	CONFIG_BIND: "Config.bind",
	CONFIG_LENGTH: "Config.length",
	CONTROL_PREVENT_DEFAULT: "Control.preventDefault",
	CONTROL_GAMEPADS: "Control.gamepads",
	CONTROL_ON: "Control.on",
	CONTROL_EMIT: "Control.emit",
	CONTROL_LISTEN: "Control.listen",
	CONTROL_INIT: "Control.init",
	GUI_TEMPLATE: "GUI.template",
	GUI_REMOVE: "GUI.remove",
	GUI_PUT: "GUI.put",
	GUI_GET: "GUI.get",
	GUI_MAKE: "GUI.make",
	GUI_SET: "GUI.set",
	GUI_ON: "GUI.on",
	GUI_EMIT: "GUI.emit",
	DRAW_REGISTER_TEXTURE:"Draw.registerTexture",
	DRAW_MAKE_SPRITE:"Draw.makeSprite",
	DRAW_GET_TEXTURE:"Draw.getTexture",
	DRAW_NEW_GRAPHIC: "Draw.newGraphic",
	DRAW_GET_GRAPHIC: "Draw.getGraphic",
	DRAW_CLEAR: "Draw.clear",
	DRAW_CHANGE: "Draw.change",
	DRAW_POLY: "Draw.poly",
	DRAW_MOVE: "Draw.move",
	DRAW_SETUP: "Draw.setup",
	HELP_ITEM_REMOVE: "Help.itemRemove",
	HELP_INDEX_REMOVE: "Help.indexRemove",
	HELP_HAS: "Help.has",
	HELP_SPLICE: "Help.splice",
	LIGHT_SOURCE: "Light.source",
	LIGHT_VIEW: "Light.view",
	LIGHT_WALL: "Light.wall",
	LIGHT_PARSE: "Light.parse",
	LIGHT_ADD_LIGHT: "Light.addLight",
	LIGHT_ADD_VIEW: "Light.addViewPort",
	LIGHT_ADD_WALL: "Light.addWall",
	LIST_CLEAN:"List.clean",
	LIST_SIZE: "List.size",
	LIST_GET: "List.get",
	LIST_PUT: "List.put",
	LIST_LINKED: "List.linked",
	LOOP_GO: "Loop.go",
	LOOP_EVERY: "Loop.every",
	LOOP_ON: "Loop.on",
	MAP_MAKE:"Map.make",
	MAP_DRAW:"Map.draw",
	MAP_MOVE:"Map.move",
	PHYSICS_TEST: "Physics.test",
	PHYSICS_GET_VERTICES: "Physics.getVertices",
	PLAYER_LENGTH: "Player.length",
	PLAYER_REGISTER: "Player.register",
	PLAYER_FIND: "Player.find",
	PLAYER_INIT: "Player.init",
	PLAYER_IS_LOCAL: "Player.isLocal",
	PLAYER_TOGGLE_PLAYER: "Player.togglePlayer",
	RIFFWAVE_LENGTH: "RiffWave.length",
	RIFFWAVE_GET: "RiffWave.get",
	RIFFWAVE_MAKE: "RiffWave.make",
	STRUCT_MAKE: "Struct.make",
	STRUCT_GET: "Struct.get",
	TIME_NOW: "Time.now",
	TIME_MICRO: "Time.micro",
};

for (var attr in engineNames) {
	options.compress.global_defs[attr] = engineNames[attr];
}

for (var attr in singleNames) {
	options.compress.global_defs[attr] = singleNames[attr];
}

for (var attr in constNames) {
	options.compress.global_defs[attr] = constNames[attr];
}

module.exports = {
	options: options,
	singleNames: singleNames,
	engineNames: engineNames,
	constNames: constNames
};